// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Master parameter table with versioning support
type Parameter struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
	// Parameter category: transaction_limit, rate, fee, regulatory, operational_hours, approval_threshold, authorization_limit
	Category string `json:"category"`
	Name     string `json:"name"`
	// Entity type this parameter applies to: role, customer_type, product, global, branch, user
	AppliesTo   string      `json:"applies_to"`
	AppliesToID pgtype.Text `json:"applies_to_id"`
	Product     pgtype.Text `json:"product"`
	// JSONB value - can be number, string, object, or array
	Value          []byte             `json:"value"`
	ValueType      string             `json:"value_type"`
	Unit           pgtype.Text        `json:"unit"`
	Scope          pgtype.Text        `json:"scope"`
	EffectiveFrom  pgtype.Timestamptz `json:"effective_from"`
	EffectiveUntil pgtype.Timestamptz `json:"effective_until"`
	Version        int32              `json:"version"`
	// Only one version active at a time per parameter combination
	IsActive  bool               `json:"is_active"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Metadata and configuration for parameter categories
type ParameterCategory struct {
	ID           pgtype.UUID        `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	ValueSchema  []byte             `json:"value_schema"`
	DefaultValue []byte             `json:"default_value"`
	DisplayOrder pgtype.Int4        `json:"display_order"`
	Icon         pgtype.Text        `json:"icon"`
	Color        pgtype.Text        `json:"color"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Audit trail for all parameter changes
type ParameterHistory struct {
	ID              pgtype.UUID `json:"id"`
	ParameterID     pgtype.UUID `json:"parameter_id"`
	OrgID           pgtype.UUID `json:"org_id"`
	PreviousValue   []byte      `json:"previous_value"`
	NewValue        []byte      `json:"new_value"`
	ChangeType      string      `json:"change_type"`
	PreviousVersion pgtype.Int4 `json:"previous_version"`
	NewVersion      int32       `json:"new_version"`
	// Required for update operations - business justification
	ChangeReason   pgtype.Text        `json:"change_reason"`
	ChangeMetadata []byte             `json:"change_metadata"`
	ChangedBy      pgtype.UUID        `json:"changed_by"`
	ChangedAt      pgtype.Timestamptz `json:"changed_at"`
}
