// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type BranchScope struct {
	BranchID       pgtype.UUID        `json:"branch_id"`
	OrgID          pgtype.UUID        `json:"org_id"`
	BranchType     string             `json:"branch_type"`
	ParentBranchID pgtype.UUID        `json:"parent_branch_id"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SyncedAt       pgtype.Timestamptz `json:"synced_at"`
}

type Parameter struct {
	ID             pgtype.UUID        `json:"id"`
	OrgID          pgtype.UUID        `json:"org_id"`
	Category       string             `json:"category"`
	Name           string             `json:"name"`
	AppliesTo      string             `json:"applies_to"`
	AppliesToID    pgtype.Text        `json:"applies_to_id"`
	Product        pgtype.Text        `json:"product"`
	Value          json.RawMessage    `json:"value"`
	ValueType      string             `json:"value_type"`
	Unit           pgtype.Text        `json:"unit"`
	Scope          pgtype.Text        `json:"scope"`
	EffectiveFrom  pgtype.Timestamptz `json:"effective_from"`
	EffectiveUntil pgtype.Timestamptz `json:"effective_until"`
	Version        int32              `json:"version"`
	IsActive       bool               `json:"is_active"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ParameterCategory struct {
	ID           pgtype.UUID        `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	ValueSchema  json.RawMessage    `json:"value_schema"`
	DefaultValue json.RawMessage    `json:"default_value"`
	DisplayOrder int32              `json:"display_order"`
	Icon         pgtype.Text        `json:"icon"`
	Color        pgtype.Text        `json:"color"`
	IsActive     bool               `json:"is_active"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ParameterHistory struct {
	ID              pgtype.UUID        `json:"id"`
	ParameterID     pgtype.UUID        `json:"parameter_id"`
	OrgID           pgtype.UUID        `json:"org_id"`
	PreviousValue   json.RawMessage    `json:"previous_value"`
	NewValue        json.RawMessage    `json:"new_value"`
	ChangeType      string             `json:"change_type"`
	PreviousVersion int32              `json:"previous_version"`
	NewVersion      int32              `json:"new_version"`
	ChangeReason    string             `json:"change_reason"`
	ChangeMetadata  json.RawMessage    `json:"change_metadata"`
	ChangedBy       pgtype.UUID        `json:"changed_by"`
	ChangedAt       pgtype.Timestamptz `json:"changed_at"`
}
