// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParameter = `-- name: CreateParameter :one
INSERT INTO parameters (
  org_id, category, name, applies_to, applies_to_id, product, 
  value, value_type, unit, scope, effective_from, effective_until, 
  version, is_active, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, org_id, category, name, applies_to, applies_to_id, product, value, value_type, unit, scope, effective_from, effective_until, version, is_active, created_by, created_at, updated_at
`

type CreateParameterParams struct {
	OrgID          pgtype.UUID        `json:"org_id"`
	Category       string             `json:"category"`
	Name           string             `json:"name"`
	AppliesTo      string             `json:"applies_to"`
	AppliesToID    pgtype.Text        `json:"applies_to_id"`
	Product        pgtype.Text        `json:"product"`
	Value          []byte             `json:"value"`
	ValueType      string             `json:"value_type"`
	Unit           pgtype.Text        `json:"unit"`
	Scope          pgtype.Text        `json:"scope"`
	EffectiveFrom  pgtype.Timestamptz `json:"effective_from"`
	EffectiveUntil pgtype.Timestamptz `json:"effective_until"`
	Version        int32              `json:"version"`
	IsActive       bool               `json:"is_active"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateParameter(ctx context.Context, arg CreateParameterParams) (Parameter, error) {
	row := q.db.QueryRow(ctx, createParameter,
		arg.OrgID,
		arg.Category,
		arg.Name,
		arg.AppliesTo,
		arg.AppliesToID,
		arg.Product,
		arg.Value,
		arg.ValueType,
		arg.Unit,
		arg.Scope,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.Version,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i Parameter
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Category,
		&i.Name,
		&i.AppliesTo,
		&i.AppliesToID,
		&i.Product,
		&i.Value,
		&i.ValueType,
		&i.Unit,
		&i.Scope,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.Version,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createParameterHistory = `-- name: CreateParameterHistory :one
INSERT INTO parameter_history (
    parameter_id, org_id, previous_value, new_value,
    change_type, previous_version, new_version, change_reason,
    change_metadata, changed_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, parameter_id, org_id, previous_value, new_value, change_type, previous_version, new_version, change_reason, change_metadata, changed_by, changed_at
`

type CreateParameterHistoryParams struct {
	ParameterID     pgtype.UUID `json:"parameter_id"`
	OrgID           pgtype.UUID `json:"org_id"`
	PreviousValue   []byte      `json:"previous_value"`
	NewValue        []byte      `json:"new_value"`
	ChangeType      string      `json:"change_type"`
	PreviousVersion pgtype.Int4 `json:"previous_version"`
	NewVersion      int32       `json:"new_version"`
	ChangeReason    pgtype.Text `json:"change_reason"`
	ChangeMetadata  []byte      `json:"change_metadata"`
	ChangedBy       pgtype.UUID `json:"changed_by"`
}

func (q *Queries) CreateParameterHistory(ctx context.Context, arg CreateParameterHistoryParams) (ParameterHistory, error) {
	row := q.db.QueryRow(ctx, createParameterHistory,
		arg.ParameterID,
		arg.OrgID,
		arg.PreviousValue,
		arg.NewValue,
		arg.ChangeType,
		arg.PreviousVersion,
		arg.NewVersion,
		arg.ChangeReason,
		arg.ChangeMetadata,
		arg.ChangedBy,
	)
	var i ParameterHistory
	err := row.Scan(
		&i.ID,
		&i.ParameterID,
		&i.OrgID,
		&i.PreviousValue,
		&i.NewValue,
		&i.ChangeType,
		&i.PreviousVersion,
		&i.NewVersion,
		&i.ChangeReason,
		&i.ChangeMetadata,
		&i.ChangedBy,
		&i.ChangedAt,
	)
	return i, err
}

const deactivateParameter = `-- name: DeactivateParameter :exec
UPDATE parameters
SET is_active = FALSE, updated_at = NOW()
WHERE id = $1 AND org_id = $2
`

type DeactivateParameterParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) DeactivateParameter(ctx context.Context, arg DeactivateParameterParams) error {
	_, err := q.db.Exec(ctx, deactivateParameter, arg.ID, arg.OrgID)
	return err
}

const getParameter = `-- name: GetParameter :one
SELECT id, org_id, category, name, applies_to, applies_to_id, product, value, value_type, unit, scope, effective_from, effective_until, version, is_active, created_by, created_at, updated_at
FROM parameters
WHERE org_id = $1
  AND category = $2
  AND name = $3
  AND applies_to = $4
  AND (applies_to_id = $5 OR ($5::varchar IS NULL AND applies_to_id IS NULL))
  AND (product = $6 OR ($6::varchar IS NULL AND product IS NULL))
  AND is_active = TRUE
  AND effective_from <= NOW()
  AND (effective_until IS NULL OR effective_until > NOW())
ORDER BY version DESC
LIMIT 1
`

type GetParameterParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	Category    string      `json:"category"`
	Name        string      `json:"name"`
	AppliesTo   string      `json:"applies_to"`
	AppliesToID pgtype.Text `json:"applies_to_id"`
	Product     pgtype.Text `json:"product"`
}

func (q *Queries) GetParameter(ctx context.Context, arg GetParameterParams) (Parameter, error) {
	row := q.db.QueryRow(ctx, getParameter,
		arg.OrgID,
		arg.Category,
		arg.Name,
		arg.AppliesTo,
		arg.AppliesToID,
		arg.Product,
	)
	var i Parameter
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Category,
		&i.Name,
		&i.AppliesTo,
		&i.AppliesToID,
		&i.Product,
		&i.Value,
		&i.ValueType,
		&i.Unit,
		&i.Scope,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.Version,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParameterByID = `-- name: GetParameterByID :one
SELECT id, org_id, category, name, applies_to, applies_to_id, product, value, value_type, unit, scope, effective_from, effective_until, version, is_active, created_by, created_at, updated_at FROM parameters WHERE id = $1 AND org_id = $2
`

type GetParameterByIDParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetParameterByID(ctx context.Context, arg GetParameterByIDParams) (Parameter, error) {
	row := q.db.QueryRow(ctx, getParameterByID, arg.ID, arg.OrgID)
	var i Parameter
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Category,
		&i.Name,
		&i.AppliesTo,
		&i.AppliesToID,
		&i.Product,
		&i.Value,
		&i.ValueType,
		&i.Unit,
		&i.Scope,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.Version,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParameterHistory = `-- name: GetParameterHistory :many
SELECT id, parameter_id, org_id, previous_value, new_value, change_type, previous_version, new_version, change_reason, change_metadata, changed_by, changed_at FROM parameter_history
WHERE parameter_id = $1 AND org_id = $2
ORDER BY changed_at DESC
`

type GetParameterHistoryParams struct {
	ParameterID pgtype.UUID `json:"parameter_id"`
	OrgID       pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetParameterHistory(ctx context.Context, arg GetParameterHistoryParams) ([]ParameterHistory, error) {
	rows, err := q.db.Query(ctx, getParameterHistory, arg.ParameterID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParameterHistory{}
	for rows.Next() {
		var i ParameterHistory
		if err := rows.Scan(
			&i.ID,
			&i.ParameterID,
			&i.OrgID,
			&i.PreviousValue,
			&i.NewValue,
			&i.ChangeType,
			&i.PreviousVersion,
			&i.NewVersion,
			&i.ChangeReason,
			&i.ChangeMetadata,
			&i.ChangedBy,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParameters = `-- name: ListParameters :many
SELECT id, org_id, category, name, applies_to, applies_to_id, product, value, value_type, unit, scope, effective_from, effective_until, version, is_active, created_by, created_at, updated_at FROM parameters
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListParametersParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListParameters(ctx context.Context, arg ListParametersParams) ([]Parameter, error) {
	rows, err := q.db.Query(ctx, listParameters, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Parameter{}
	for rows.Next() {
		var i Parameter
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Category,
			&i.Name,
			&i.AppliesTo,
			&i.AppliesToID,
			&i.Product,
			&i.Value,
			&i.ValueType,
			&i.Unit,
			&i.Scope,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.Version,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
