// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	CreateParameter(ctx context.Context, arg CreateParameterParams) (Parameter, error)
	CreateParameterHistory(ctx context.Context, arg CreateParameterHistoryParams) (ParameterHistory, error)
	DeactivateParameter(ctx context.Context, arg DeactivateParameterParams) error
	GetParameter(ctx context.Context, arg GetParameterParams) (Parameter, error)
	GetParameterByID(ctx context.Context, arg GetParameterByIDParams) (Parameter, error)
	GetParameterHistory(ctx context.Context, arg GetParameterHistoryParams) ([]ParameterHistory, error)
	ListParameters(ctx context.Context, arg ListParametersParams) ([]Parameter, error)
}

var _ Querier = (*Queries)(nil)
