name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install sqlc
      run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

    - name: Run sqlc generate
      run: sqlc generate

    - name: Build
      run: go build -v ./cmd/server

    - name: Test
      run: go test -v ./...
